# 预处理

## 数据无量纲化

In [41]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
import pandas as pd
pd.DataFrame(data)


0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

压缩到[0,1]

In [42]:
scaler=MinMaxScaler()
result=scaler.fit_transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

范围要使用元组

In [43]:
scaler=MinMaxScaler(feature_range=(5,8))
result=scaler.fit_transform(data)
result

array([[5.  , 5.  ],
       [5.75, 5.75],
       [6.5 , 6.5 ],
       [8.  , 8.  ]])

标准化

In [44]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
result2=scaler.fit_transform(data)


## 填充

| 参数              | 含义&输入                                                                                                                                                                  |
|-----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| missing_values  | 告诉SimpleImputer，数据中缺失值是什么，默认空值np.nan                                                                                                              |
| strategy        | <ul><li>我们填补缺失值的策略，默认均值。</li><li>输入`"mean"`使用均值填补（仅对数值特征的值）。</li><li>输入`"median"`使用中位值填补（仅对数值特征的值）。</li><li>输入`"most_frequent"`使用众数填补（对数值型和字符特征的值）。</li><li>输入`"constant"`表示常量，常量值需要选择`fill_value`中的值（对数值型和字符特征的值）。</li></ul> |
| fill_value      | 当参数strategy为`"constant"`时使用，输入法字符或数值来替换丢失的值，常用0                                                                                                 |
| copy            | 默认值为True，保持数据集去拷贝值的填补，反之减少内存消耗同样的数据。                                                                                                   |

In [45]:
data=pd.read_csv(r"day08_Narrativedata.csv",index_col=0)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [46]:
from sklearn.impute import SimpleImputer
imp_mean=SimpleImputer()
imp_median=SimpleImputer(strategy="median")
age=data.loc[:,"Age"].values.reshape(-1,1)
age

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [  nan],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [  nan],
       [31.  ],
       [  nan],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [  nan],
       [19.  ],
       [  nan],
       [  nan],
       [40.  ],
       [  nan],
       [  nan],
       [66.  ],
       [28.  ],
       [42.  ],
       [  nan],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [  nan],
       [ 3.  ],
       [19.  ],
       [  nan],
       [  nan],
       [  nan],
       [  nan],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [  nan],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [47]:
imp_mean = imp_mean.fit_transform(age)
imp_median=imp_median.fit_transform(age)
imp_mean

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29

In [48]:
data.loc[:,"Age"]=imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [49]:
Embarked = data.loc[:,"Embarked"].values.reshape(-1,1)
imp_mode = SimpleImputer(strategy = "most_frequent")
data.loc[:,"Embarked"] = imp_mode.fit_transform(Embarked)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [50]:
from sklearn.preprocessing import LabelEncoder
y=data.iloc[:,-1]
y

0           No
1          Yes
2          Yes
3          Yes
4           No
        ...   
886         No
887        Yes
888         No
889    Unknown
890         No
Name: Survived, Length: 891, dtype: object

In [54]:
le=LabelEncoder()
le=le.fit(y)
le.classes_ 
label=le.transform(y)
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [55]:
data.iloc[:,-1]=label
data.head()

Age     Sex Embarked Survived
0  22.0    male        S        0
1  38.0  female        C        2
2  26.0  female        S        2
3  35.0  female        S        2
4  35.0    male        S        0

In [58]:
from sklearn.preprocessing  import OrdinalEncoder
OrdinalEncoder().fit(data.iloc[:,1:-1]).categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [59]:
from sklearn.preprocessing import OneHotEncoder
X = data.iloc[:,1:-1]
enc = OneHotEncoder(categories='auto').fit(X)
result = enc.transform(X).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [61]:
data=pd.concat([data,pd.DataFrame(result)],axis=1)
data.head

<bound method NDFrame.head of       Age     Sex Embarked Survived    0    1    2    3    4
0    22.0    male        S        0  0.0  1.0  0.0  0.0  1.0
1    38.0  female        C        2  1.0  0.0  1.0  0.0  0.0
2    26.0  female        S        2  1.0  0.0  0.0  0.0  1.0
3    35.0  female        S        2  1.0  0.0  0.0  0.0  1.0
4    35.0    male        S        0  0.0  1.0  0.0  0.0  1.0
..    ...     ...      ...      ...  ...  ...  ...  ...  ...
886  27.0    male        S        0  0.0  1.0  0.0  0.0  1.0
887  19.0  female        S        2  1.0  0.0  0.0  0.0  1.0
888  28.0  female        S        0  1.0  0.0  0.0  0.0  1.0
889  26.0    male        C        1  0.0  1.0  1.0  0.0  0.0
890  32.0    male        Q        0  0.0  1.0  0.0  1.0  0.0

[891 rows x 9 columns]>

In [62]:
data.drop(["Sex","Embarked"],axis=1,inplace=True)

In [63]:
data

Age Survived    0    1    2    3    4
0    22.0        0  0.0  1.0  0.0  0.0  1.0
1    38.0        2  1.0  0.0  1.0  0.0  0.0
2    26.0        2  1.0  0.0  0.0  0.0  1.0
3    35.0        2  1.0  0.0  0.0  0.0  1.0
4    35.0        0  0.0  1.0  0.0  0.0  1.0
..    ...      ...  ...  ...  ...  ...  ...
886  27.0        0  0.0  1.0  0.0  0.0  1.0
887  19.0        2  1.0  0.0  0.0  0.0  1.0
888  28.0        0  1.0  0.0  0.0  0.0  1.0
889  26.0        1  0.0  1.0  1.0  0.0  0.0
890  32.0        0  0.0  1.0  0.0  1.0  0.0

[891 rows x 7 columns]

# 特征选择

## 过滤法

方差

In [67]:
from sklearn.feature_selection import VarianceThreshold
data=pd.read_csv(r"day08_digit recognizor.csv")
x=data.iloc[:,1:]
y=data.iloc[:,0]
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 784 entries, pixel0 to pixel783
dtypes: int64(784)
memory usage: 251.2 MB


In [74]:

selector=VarianceThreshold()

x_var0=selector.fit_transform(x)
x_var0.shape

(42000, 708)

In [76]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
rfc=RandomForestClassifier(n_estimators=15,random_state=1)
cross_val_score(rfc,x,y,cv=10).mean()

0.9489285714285713

In [82]:
cross_val_score(rfc,x_var0,y,cv=11).mean()

0.9504284927045678

### 卡方过滤

In [80]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
x_chi=SelectKBest(chi2,k=300).fit_transform(x,y)
x_chi.shape

(42000, 300)

In [81]:
cross_val_score(rfc,x_chi,y,cv=11).mean()

0.9451189966140233

### **F检验**  
它即可以做回归也
可以做分类，因此包含feature_selection.f_classif（F检验分类）和feature_selection.f_regression（F检验回
归）两个类。

In [85]:
from sklearn.feature_selection import f_classif
F,p=f_classif(x,y)
k=F.shape[0]-(p>0.05).sum()
k

d:\Users\admin\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [  0   1   2   3   4   5   6   7   8   9  10  11  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  52  53  54  55  56  57  82  83
  84  85 111 112 139 140 141 168 196 392 420 421 448 476 532 560 644 645
 671 672 673 699 700 701 727 728 729 730 731 754 755 756 757 758 759 760
 780 781 782 783] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
d:\Users\admin\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


736

In [86]:
x_f=SelectKBest(f_classif,k=k).fit_transform(x,y)
x_f.shape

d:\Users\admin\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [  0   1   2   3   4   5   6   7   8   9  10  11  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  52  53  54  55  56  57  82  83
  84  85 111 112 139 140 141 168 196 392 420 421 448 476 532 560 644 645
 671 672 673 699 700 701 727 728 729 730 731 754 755 756 757 758 759 760
 780 781 782 783] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
d:\Users\admin\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


(42000, 736)

### **互信息法**  
互信息法不返回p值或F值类似的统计量，它返回“每个特征与目标之间的互信息量的估计”，这个估计量在[0,1]之间
取值，为0则表示两个变量独立，为1则表示两个变量完全相关。

In [87]:
from sklearn.feature_selection import mutual_info_classif
result = mutual_info_classif(x,y)
k=result.shape[0]-sum(result<=0)
k

699

### 过滤法总结

| 类 | 说明 | 超参数的选择 |
|---|---|---|
| VarianceThreshold | 方差过滤，可输入方差阈值，返回方差大于阈值的新特征矩阵 | 看具体数据究竟是含有更多噪声还是更多有效特征一般就使用0或1来筂选也可以画学习曲线或取中位数跑模型来帮助确认 |
| SelectKBest | 用来选取K个统计量结果最佳的特征，生成符合统计量要求的新特征矩阵 | 看配合使用的统计量 |
| chi2 | 卡方检验，专用于分类算法，捕捉相关性 | 追求p小于显著性水平的特征 |
| f_classif | F检验分类，只能捕捉线性相关性要求数据服从正态分布 | 追求p小于显著性水平的特征 |
| f_regression | F检验回归，只能捕捉线性相关性要求数据服从正态分布 | 追求 $p$ 小于显著性水平的特征 |
| mutual_info_classif | 互信息分类，可以捕捉任何相关性不能用于稀疏矩阵 | 追求互信息估计大于0的特征 |
| mutual_info_regression | 互信息回归，可以捕捉任何相关性不能用于稀疏矩阵 | 追求互信息估计大于0的特征 |

## 嵌入法

In [89]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier as RFC
RFC_ = RFC(n_estimators =10,random_state=0)
x_embedded = SelectFromModel(RFC_,threshold=0.005).fit_transform(x,y)
x_embedded.shape

(42000, 47)

## 包装法

In [92]:
from sklearn.feature_selection import RFE
RFC_ = RFC(n_estimators =10,random_state=0)
selector = RFE(RFC_, n_features_to_select=340, step=50).fit(x, y)
selector.support_.sum()


340

In [93]:
X_wrapper = selector.transform(x)
cross_val_score(RFC_,X_wrapper,y,cv=5).mean()

0.9379761904761905